### ISSUE TITLE
AURA IDEX SWAP NO MORE STACKING

### ISSUE THREAD

**Issue by elhios** [idexio/IDEXd#3]
Staking: offline [Wed May 08 2019 23:21:24 GMT+0000 (GMT)]
Status: Your staker is out of sync with the blockchain

**Comment by elhios** [comment]
~/idex » idex status                                                                                                                                                                                                                                                                                                        elhios@chtitbox
idexd-cli v0.2.1
Latest version: v0.2.1
Cold wallet: 0x555D75370A14a7fbe245Db702719b4A1C6C140f8
Staked IDEX: 10969.16 IDEX 
Total Staked IDEX: 87825012.99 IDEX
Staking: offline [Wed May 08 2019 23:32:04 GMT+0000 (GMT)]
Current period: Mon Apr 29 2019 12:00:00 GMT+0000 to Sun May 12 2019 11:59:59 GMT+0000
My Period Credits/Total Period Credits: 2511.02 / 24094594 (0.01%)
Last period earnings: 0.000000 ETH
Last period credits: 0.00 / 34551311 (0.00%)
Earnings History: To access your complete earnings history, visit here: https://reporting.idex.market/aurad/earnings/bc4d28e0b7039fa400e63c3c2354b5f1
Further Information: For further details on this information, please refer to the full documentation: https://github.com/idexio/idexd

**Comment by yennieb** [comment]
@elhios this message is normal, if your node is currently synching. You should be able to see what block it is currently processing by viewing the logs. You can tail them with the following if you want to follow the progress:

`docker logs -f docker_idexd_1`

**Comment by elhios** [comment]
Thx a lot. Very efficient support. :)

**Comment by elhios** [comment]
Now I've got this.

09:59:33 0|worker  | Processing blocks 7751332 to 7751334
09:59:38 0|worker  | STAKING OFFLINE: Your staker is out of sync with the blockchain
09:59:38 PM2       | Change detected on path downtime.log for app worker - restarting
2019-05-13T09:59:39: PM2 log: Stopping app:worker id:0
09:59:39 PM2       | Stopping app:worker id:0
09:59:39 0|worker  | SIGINT signal received.
2019-05-13T09:59:39: PM2 log: App [worker:0] exited with code [1] via signal [SIGINT]
2019-05-13T09:59:39: PM2 log: App [worker:0] will restart in 1000ms
09:59:39 PM2       | App [worker:0] exited with code [1] via signal [SIGINT]
09:59:39 PM2       | App [worker:0] will restart in 1000ms
2019-05-13T09:59:39: PM2 log: pid=3005 msg=process killed
2019-05-13T09:59:39: PM2 log: App [worker:0] starting in -fork mode-
09:59:39 PM2       | pid=3005 msg=process killed
09:59:39 PM2       | App [worker:0] starting in -fork mode-
2019-05-13T09:59:39: PM2 log: App [worker:0] online
09:59:39 PM2       | App [worker:0] online
09:59:40 0|worker  | Mon, 13 May 2019 09:59:40 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
09:59:40 0|worker  | (node:3377) ExperimentalWarning: The fs.promises API is experimental
09:59:41 0|worker  | Sequelize CLI [Node: 10.15.3, CLI: 5.4.0, ORM: 4.41.2]
09:59:41 0|worker  | Loaded configuration file "lib/sequelize_config.js".
09:59:41 0|worker  | Using environment "development".
09:59:41 0|worker  | Mon, 13 May 2019 09:59:41 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
09:59:41 0|worker  | No migrations were executed, database schema was already up to date.
09:59:41 0|worker  | API listening on port 8443
09:59:42 0|worker  | Resumed sync at block 7751300
09:59:42 0|worker  | Processing blocks 7751300 to 7751309
09:59:42 0|worker  | STAKING OFFLINE: Your staker is out of sync with the blockchain
09:59:48 0|worker  | Error processing transactions, retry in 5 seconds
09:59:53 0|worker  | Processing blocks 7751300 to 7751309
10:00:03 0|worker  | Processing blocks 7751310 to 7751319
10:00:09 0|worker  | Error processing transactions, retry in 5 seconds
10:00:12 0|worker  | STAKING OFFLINE: Your staker is out of sync with the blockchain
10:00:14 0|worker  | Processing blocks 7751310 to 7751319
10:00:20 0|worker  | Error processing transactions, retry in 5 seconds
10:00:25 0|worker  | Processing blocks 7751310 to 7751319
2019-05-13T10:00:32: PM2 log: [PM2][WORKER] Reset the restart delay, as app worker is up for more than 30000
10:00:32 PM2       | [PM2][WORKER] Reset the restart delay, as app worker is up for more than 30000
10:00:38 0|worker  | Error processing transactions, retry in 5 seconds
10:00:42 0|worker  | STAKING OFFLINE: Your staker is out of sync with the blockchain
10:00:43 0|worker  | Processing blocks 7751310 to 7751319
10:00:49 0|worker  | Error processing transactions, retry in 5 seconds

**Comment by elhios** [comment]
In fact it stop and restart permanently

**Comment by elhios** [comment]
Now i can't do docker logs -f docker_idexd_1 anymore this log is from `idex logs`

**Comment by elhios** [comment]
`idex status `
gives 
`Staked IDEX: 10969.16 IDEX 
Total Staked IDEX: 93383557.75 IDEX
Staking: offline [Mon May 13 2019 10:33:12 GMT+0000 (GMT)]
Status: Your staker is out of sync with the blockchain`

**Comment by elhios** [comment]
`docker ps -a` gives 
~ » docker ps -a                                                                                 
```
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                  PORTS                                                                                                                                               NAMES
2ddadac7f154        idexio/idexd:0.2.0            "pm2 start pm2.confi…"   10 hours ago        Up 10 hours (healthy)   0.0.0.0:8080->8080/tcp, 0.0.0.0:8443->8443/tcp                                                                                                      docker_idexd_1_7b83c67d38cd
54a48ba9e46a        mysql:5.7                     "docker-entrypoint.s…"   10 hours ago        Up 10 hours             33060/tcp, 127.0.0.1:33006->3306/tcp                                                                                                                docker_mysql_1_91a2f72b2d87
bdc093c4428e        parity/parity:stable          "/bin/parity --light…"   10 hours ago        Up 10 hours (healthy)   5001/tcp, 8080/tcp, 8082-8083/tcp, 0.0.0.0:8546->8546/tcp, 8180/tcp, 127.0.0.1:8545->8545/tcp, 0.0.0.0:30303->30303/tcp, 0.0.0.0:30303->30303/udp   docker_parity_1_63e53a2b2903

```

**Comment by elhios** [comment]
`~ » docker ps -a                                                                                  elhios@chtitbox
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                  PORTS                                                                                                                                               NAMES
2ddadac7f154        idexio/idexd:0.2.0            "pm2 start pm2.confi…"   10 hours ago        Up 10 hours (healthy)   0.0.0.0:8080->8080/tcp, 0.0.0.0:8443->8443/tcp                                                                                                      docker_idexd_1_7b83c67d38cd
54a48ba9e46a        mysql:5.7                     "docker-entrypoint.s…"   10 hours ago        Up 10 hours             33060/tcp, 127.0.0.1:33006->3306/tcp                                                                                                                docker_mysql_1_91a2f72b2d87
bdc093c4428e        parity/parity:stable          "/bin/parity --light…"   10 hours ago        Up 10 hours (healthy)   5001/tcp, 8080/tcp, 8082-8083/tcp, 0.0.0.0:8546->8546/tcp, 8180/tcp, 127.0.0.1:8545->8545/tcp, 0.0.0.0:30303->30303/tcp, 0.0.0.0:30303->30303/udp   docker_parity_1_63e53a2b2903`

**Comment by elhios** [comment]
I restarted it its ok now.
