### ISSUE TITLE
CPU Requirements?

### ISSUE THREAD

**Issue by golebioto** [idexio/IDEXd#9]
What are the recommended CPU requirements for an IDEX node?
I've been running a 1 CPU instances on AWS and it appeared to be pegged at 99% CPU usage at times so moved to a 2 CPU instance. Load seems to vary between 1 few percent to 180ish at times. Anyone else experiencing this? Are these just very high load times or is there anything else to consider?

>top - 04:18:53 up 1 day, 13 min,  1 user,  load average: 2.70, 2.66, 2.50
Tasks: 113 total,   3 running,  73 sleeping,   0 stopped,   0 zombie
%Cpu(s): 12.8 us,  7.6 sy,  0.0 ni, 28.1 id,  0.0 wa,  0.0 hi,  0.2 si, 51.3 st
KiB Mem :  4038200 total,   178468 free,   969180 used,  2890552 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  2785284 avail Mem

>  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 6808 root      20   0 1304528 193892  12672 R 139.3  4.8   1920:16 node /usr/idexd
25845 root      20   0 1203384  50352  26400 S   1.0  1.2   8:41.80 containerd
    7 root      20   0       0      0      0 S   0.3  0.0   5:47.48 ksoftirqd/0
 5266 ubuntu    20   0   44552   3988   3376 R   0.3  0.1   0:00.89 top
    1 root      20   0  159892   7236   4724 S   0.0  0.2   0:49.49 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.02 kthreadd

**Comment by dahifi** [comment]
Did you offload parity? I'm actually running on a t2.micro AWS instance after configuring my instance to use https://infura.io for the Eth node. 

This was actually recommended by IDEX staff in Discord.

**Comment by golebioto** [comment]
Apologies, I have not closed this issue. Offloading to infura.io has resolved the intermittent downtime and CPU overhead.
